export type Location = { id: string; name: string; region: string; point: [number,number]; zoom: number; kind: 'energy'|'trade'|'conflict'; goods: string[]; description: string; impact: string; source: string; sourceName: string };
const eia='https://www.eia.gov/international/content/analysis/special_topics/World_Oil_Transit_Chokepoints/';
export const locations: Location[] = [
{id:'hormuz',name:'Strait of Hormuz',region:'PERSIAN GULF',point:[26.56,56.25],zoom:6,kind:'energy',goods:['Crude oil','LNG','Refined fuels'],description:'The narrow connection between the Persian Gulf and Gulf of Oman. A critical outlet for Gulf energy exports to global markets.',impact:'Disruption can delay oil and LNG cargoes and increase shipping costs. Some oil can move through pipelines, but alternatives have limited capacity.',source:eia,sourceName:'U.S. Energy Information Administration'},
{id:'black-sea',name:'Ukraine & Black Sea',region:'EASTERN EUROPE',point:[44,31.5],zoom:6,kind:'conflict',goods:['Grain','Sunflower oil','Metals'],description:'Ukraine’s Black Sea ports connect its agricultural and industrial exports to world markets through the Turkish Straits.',impact:'Russia’s war against Ukraine has disrupted ports and shipping. Maritime exports and overland EU solidarity lanes form different parts of the trade network. This layer shows trade context, not front lines or live attacks.',source:'https://www.consilium.europa.eu/en/policies/ukraine-solidarity-supporting-ukraine-trade/',sourceName:'Council of the European Union'},
{id:'suez',name:'Suez Canal',region:'EGYPT',point:[30.5,32.35],zoom:6,kind:'trade',goods:['Containers','Oil','LNG'],description:'The canal connects the Mediterranean and Red Sea, shortening voyages between Europe and Asia.',impact:'An interruption can send vessels around southern Africa, adding distance and time. Red Sea security also affects access to this route.',source:eia,sourceName:'U.S. Energy Information Administration'},
{id:'bab',name:'Bab el-Mandeb',region:'RED SEA',point:[12.58,43.33],zoom:6,kind:'energy',goods:['Oil','Containers','LNG'],description:'The southern gateway to the Red Sea, between Yemen and the Horn of Africa.',impact:'Security disruptions can affect traffic to and from Suez and encourage diversions around the Cape of Good Hope.',source:eia,sourceName:'U.S. Energy Information Administration'},
{id:'malacca',name:'Strait of Malacca',region:'SOUTHEAST ASIA',point:[2.7,101],zoom:5,kind:'trade',goods:['Oil','Containers','LNG'],description:'A major passage between the Indian Ocean and the South China Sea, serving East Asian markets.',impact:'Congestion or interruption can shift voyages toward alternative passages through Indonesia, increasing sailing distance.',source:eia,sourceName:'U.S. Energy Information Administration'},
{id:'turkish',name:'Turkish Straits',region:'TÜRKIYE',point:[41.15,29.06],zoom:7,kind:'trade',goods:['Grain','Oil','Bulk cargo'],description:'The Bosporus and Dardanelles connect the Black Sea with the Mediterranean through the Sea of Marmara.',impact:'This passage links Black Sea export ports to ocean trade. Restrictions, weather, and congestion can delay cargoes.',source:eia,sourceName:'U.S. Energy Information Administration'},
{id:'panama',name:'Panama Canal',region:'CENTRAL AMERICA',point:[9.1,-79.7],zoom:6,kind:'trade',goods:['Containers','LPG','Grain'],description:'A canal linking the Atlantic and Pacific Oceans without sailing around South America.',impact:'Water availability and transit capacity influence waiting times and route choices.',source:eia,sourceName:'U.S. Energy Information Administration'},
{id:'cape',name:'Cape of Good Hope',region:'SOUTHERN AFRICA',point:[-34.7,18.5],zoom:4,kind:'trade',goods:['Containers','Oil','LNG'],description:'The route around southern Africa is a key alternative to the Suez and Red Sea passage.',impact:'Diversions add sailing distance, fuel use, and delivery time. The route shown is schematic, not a navigation plan.',source:eia,sourceName:'U.S. Energy Information Administration'}
];
export const routes: {name:string; kind:'energy'|'trade'|'conflict'; points:[number,number][]}[]=[
{name:'Gulf energy → Indian Ocean',kind:'energy',points:[[29,49.5],[27,51.5],[26.3,54.8],[26.56,56.25],[25.3,57.5],[23.5,60],[18,64],[8,72],[5.5,80.5],[6,89],[6,95],[3.5,99.5],[1.2,103.7],[3,106],[10,111]]},
{name:'Asia → Suez → Mediterranean',kind:'trade',points:[[1.2,103.7],[3.5,99.5],[6,95],[5.5,81],[8,72],[12,60],[12,48],[12.58,43.33],[16,41],[20,38.7],[24,36.5],[27.7,34.2],[29.9,32.55],[30.5,32.35],[31.3,32.3],[33,29],[34,23],[35,18],[37,12],[37.3,10],[37.6,7],[36.8,1],[35.9,-5.6],[36,-9],[43,-12],[48,-7]]},
{name:'Cape alternative',kind:'trade',points:[[12,60],[-2,61],[-18,56],[-28,40],[-35.5,24],[-36,18],[-32,12],[-15,3],[2,-12],[15,-20],[30,-16],[43,-12],[48,-7]]},
{name:'Black Sea export connection',kind:'conflict',points:[[46.48,30.76],[45,30.5],[43.4,29.5],[41.23,29.13],[41.02,29],[40.7,28],[40.4,26.8],[40,26.2],[39.5,25.7],[37,25],[35.2,23.5],[34,23]]},
{name:'Panama ocean connection',kind:'trade',points:[[16,-78],[11,-79],[9.35,-79.9],[9.12,-79.7],[8.9,-79.55],[7,-80],[5,-85],[0,-105]]}
];
export const ports:[string,number,number][]=[['Odesa',46.48,30.76],['Chornomorsk',46.3,30.66],['Pivdennyi',46.62,31.02],['Constanța',44.17,28.65],['Istanbul',41.01,28.97]];
