'use client';
import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import type * as Leaflet from 'leaflet';
type Vessel={mmsi:string;name:string;kind:string;destination:string|null;lat:number;lon:number;speed:number|null;heading:number|null;positionAt:number;staticAt:number|null};
type Point={time:number;aircraft:number|null;vessels:number|null};
type Feed={region:string;time:number;connected:boolean;status:string;vessels:Vessel[];aircraft:number|null;history:Point[]};
const timeLabel=(time:number)=>new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
export default function ActivityPanel({region,name,map}:{region:string;name:string;map:Leaflet.Map|null}){
 const [feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[hours,setHours]=useState(1),[selected,setSelected]=useState<string|null>(null),[cursor,setCursor]=useState<number|null>(null);
 useEffect(()=>{setFeed(null);setSelected(null);setCursor(null);setError('');let stopped=false;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
 const update=async()=>{if(document.hidden){timer=setTimeout(update,10000);return;}try{const r=await fetch('/api/activity?region='+region,{signal:controller.signal});const body=await r.json() as Feed & {error?:string};if(!r.ok)throw Error(body.error||'Activity data unavailable');if(!stopped){setFeed(body);setError('');}}catch(e){if(!stopped)setError(e instanceof Error?e.message:'Activity data unavailable');}finally{if(!stopped)timer=setTimeout(update,10000);}};void update();return()=>{stopped=true;controller.abort();clearTimeout(timer);};},[region]);
 const current=feed?.region===region?feed:null;
 useEffect(()=>{if(!map||!current)return;let layer:Leaflet.LayerGroup|undefined;let disposed=false;
 import('leaflet').then(L=>{if(disposed)return;layer=L.layerGroup().addTo(map);L.circle([mapArea[region][0],mapArea[region][1]],{radius:185200,interactive:false,color:'#63cfc7',weight:1,dashArray:'4 8',fillOpacity:.025}).addTo(layer);
 for(const v of current.vessels){const marker=L.marker([v.lat,v.lon],{title:v.name,alt:v.name,icon:L.divIcon({className:'vessel-pin'+(selected===v.mmsi?' selected':''),iconSize:[24,30],iconAnchor:[12,15],html:`<svg viewBox="0 0 24 30" style="transform:rotate(${v.heading??0}deg)" aria-hidden="true"><path d="M12 2 20 12 18 27H6L4 12Z"/></svg>`})}).addTo(layer);marker.on('click',()=>setSelected(v.mmsi));const label=document.createElement('span');label.textContent=v.name;marker.bindTooltip(label,{direction:'top'});}});return()=>{disposed=true;layer?.remove();};},[map,current,selected,region]);
 const points=(current?.history??[]).filter(p=>p.time> (current?.time??Date.now())-hours*3600000);
 // Explicit null points break lines across collection pauses and restarts.
 const chart:Point[]=[];for(const p of points){const previous=chart.at(-1);if(previous&&p.time-previous.time>120000)chart.push({time:previous.time+60000,aircraft:null,vessels:null});chart.push(p);}
 const point=cursor===null?points.at(-1):points.find(p=>p.time===cursor);const ship=current?.vessels.find(v=>v.mmsi===selected);
 return <section className="traffic-panel" aria-label="Vessel tracking and area activity"><div className="traffic-chart"><header><div><p className="eyebrow">AREA ACTIVITY · 100 NM RADIUS</p><h2>{name}</h2></div><div className="traffic-ranges" aria-label="Chart time range">{[1,6,24].map(h=><button key={h} aria-pressed={hours===h} onClick={()=>{setHours(h);setCursor(null);}}>{h}h</button>)}</div></header>
 <div className="traffic-counts"><span className="air-series">Aircraft <b>{cursor!==null?point?.aircraft??'—':error?'—':current?.aircraft??'—'}</b></span><span className="sea-series">Vessels <b>{cursor!==null?point?.vessels??'—':error||!current?.connected?'—':current.vessels.length}</b></span><small>{cursor!==null&&point?timeLabel(point.time)+' · recorded count':'Latest observations'}{error?' · stale / offline':''}</small></div>
 <div className="traffic-plot">{points.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:8,right:20,bottom:0,left:-20}}><CartesianGrid stroke="#29404f" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={timeLabel} stroke="#8aa6b7" fontSize={12}/><YAxis allowDecimals={false} stroke="#8aa6b7" fontSize={12}/><Tooltip labelFormatter={v=>timeLabel(Number(v))} contentStyle={{background:'#0d2030',border:'1px solid #426272',borderRadius:8}}/><Line name="Aircraft" dataKey="aircraft" stroke="#edbe79" strokeWidth={2} dot={{r:2}} connectNulls={false} isAnimationActive={false}/><Line name="Vessels" dataKey="vessels" stroke="#65dbd0" strokeWidth={2} dot={{r:2}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>:<p className="traffic-empty">{error||'Collecting the first observation. History starts here; no earlier counts are assumed.'}</p>}</div>
 {points.length>0&&<label className="traffic-scrubber">Inspect time <input aria-label="Inspect recorded activity time" type="range" min={0} max={points.length-1} value={cursor===null?points.length-1:Math.max(0,points.findIndex(p=>p.time===cursor))} onChange={e=>setCursor(points[Number(e.target.value)].time)}/><button onClick={()=>setCursor(null)}>Latest</button></label>}
 <p className="traffic-note">Counts of observed aircraft (positions ≤60s old) and vessels (reports received ≤10m ago), not total traffic. Gaps mean unavailable data. History is saved locally while this area is being viewed; the map always shows the latest vessel reports.</p></div>
 <aside className="traffic-vessels"><header><h2>On the water</h2><span>{current?.connected&&!error?'● Connected':'○ Offline'}</span></header><p className="traffic-note" role="status">{error||current?.status||'Connecting collector…'}</p>
 {ship?<article className="vessel-detail"><button className="vessel-back" onClick={()=>setSelected(null)}>← Vessel list</button><h3>{ship.name}</h3><dl><div><dt>Vessel type</dt><dd>{ship.kind}</dd></div><div><dt>Destination · reported</dt><dd>{ship.destination||'Not reported yet'}</dd></div><div><dt>Actual cargo / manifest</dt><dd>Not available from AIS</dd></div><div><dt>Speed</dt><dd>{ship.speed===null?'Unknown':ship.speed.toFixed(1)+' kt'}</dd></div><div><dt>MMSI</dt><dd>{ship.mmsi}</dd></div><div><dt>Position received</dt><dd>{new Date(ship.positionAt).toLocaleTimeString()}</dd></div></dl><p className="traffic-note">Destination is crew-entered and may be outdated. Vessel type does not confirm what is aboard.</p></article>:<div className="vessel-list">{current?.vessels.map(v=><button key={v.mmsi} onClick={()=>{setSelected(v.mmsi);map?.stop();map?.flyTo([v.lat,v.lon],8,{duration:.55,animate:!matchMedia('(prefers-reduced-motion: reduce)').matches});}}><span><strong>{v.name}</strong><small>{v.kind} · {v.destination||'Destination not reported'}</small></span><span>↗</span></button>)}{!current?.vessels.length&&<p className="traffic-empty">{current?.connected?'Waiting for vessel reports in this area. Coverage varies.':'Live vessels appear after the free feed is connected.'}</p>}</div>}
 <a className="traffic-source" href="https://aisstream.io/documentation" target="_blank" rel="noreferrer">AISStream</a><span className="traffic-source"> / </span><a className="traffic-source" href="https://www.adsb.lol/docs/open-data/api/" target="_blank" rel="noreferrer">ADSB.lol</a></aside></section>;
}
const mapArea:Record<string,[number,number]>={hormuz:[26.56,56.25],'black-sea':[44,31.5],suez:[30.5,32.35],bab:[12.58,43.33],malacca:[2.7,101],turkish:[41.15,29.06],panama:[9.1,-79.7],cape:[-34.7,18.5]};

